version: 0.0

os: linux

files:

– source: .

destination: /var/www/test

hooks:

ApplicationStop:

– location: scripts/application_stop.sh

timeout: 300

runas: root

ApplicationStart:

– location: scripts/application_start.sh

timeout: 300

runas: root