pipelines:
  branches:
    main:
      - parallel:
         - step:
              name: Deploying on 138.68.141.175 litespeed
              script:
                - pipe: atlassian/ssh-run:0.2.6
                  variables:
                    SSH_USER: "root"
                    SERVER: "46.101.87.41"
                    COMMAND: "/root/clone.lightspeed.sh"
                    MODE: "command"
         - step:
              name: Deploying on 46.101.41.190 litespeed
              script:
                - pipe: atlassian/ssh-run:0.2.6
                  variables:
                    SSH_USER: "root"
                    SERVER: "46.101.41.190"
                    COMMAND: "/root/clone.lightspeed.sh"
                    MODE: "command"
         - step:
              name: Deploying on 167.99.198.127 litespeed
              script:
                - pipe: atlassian/ssh-run:0.2.6
                  variables:
                    SSH_USER: "root"
                    SERVER: "167.99.198.127"
                    COMMAND: "/root/clone.lightspeed.sh"
                    MODE: "command"